kind = "web"
previewPath = "/"
title = "HealthLogix"
version = "1.0.0"
id = "artifacts/HealthLogix"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23159

[services.development]
run = "pnpm --filter @workspace/HealthLogix run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/HealthLogix", "run", "build" ]
publicDir = "artifacts/HealthLogix/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23159"
BASE_PATH = "/"
